apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wt-postgres-pvc
  namespace: wt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi