apiVersion: apps/v1
kind: Deployment
metadata:
  name: wt-web-deployment
  namespace: wt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wt-web
  template:
    metadata:
      labels:
        app: wt-web
    spec:
      containers:
      - name: wt-web-container
        image: localhost:32000/wt-books:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:foo123@wt-postgres-service:5432/wt?serverVersion=17&charset=utf8"
        - name: APP_ENV
          value: "prod"
        - name: APP_SECRET
          value: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
        - name: TZ
          value: "Europe/Vilnius"